# Generated by Django 6.0.1 on 2026-02-03 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('numero_interior', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=3)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='agenda.contacto')),
            ],
        ),
    ]
