# Generated by Django 6.0.1 on 2026-02-03 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_direccion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Casa'), (2, 'Teléfono móvil')], max_length=50)),
                ('alias', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='agenda.contacto')),
            ],
        ),
    ]
